#!/bin/sh
# Rebuild assets/tour.gif from assets/tour.cast.
#
# The cast file is the source of truth (regenerated by
# `python3 assets/generate_tour_cast.py`). The GIF is a build artifact
# rendered via agg (asciinema → gif converter).
#
# Tries `agg` on PATH first; falls back to the official Docker image if
# available; otherwise prints install instructions.
#
# Usage:
#   bash assets/build_tour_gif.sh

set -e

HERE="$(cd "$(dirname "$0")" && pwd)"
CAST="$HERE/tour.cast"
GIF="$HERE/tour.gif"

if [ ! -f "$CAST" ]; then
    echo "no cast file at $CAST — regenerating..."
    python3 "$HERE/generate_tour_cast.py"
fi

# Sensible defaults for a clean GitHub-rendered GIF.
COMMON_ARGS="--theme monokai --speed 1.4 --font-size 16 --cols 96 --rows 28"

if command -v agg >/dev/null 2>&1; then
    echo "using agg on PATH"
    # shellcheck disable=SC2086
    agg $COMMON_ARGS "$CAST" "$GIF"
elif command -v docker >/dev/null 2>&1; then
    echo "using ghcr.io/asciinema/agg via docker"
    # On Git Bash / MSYS, `pwd -W` returns the Windows-style absolute path
    # that Docker Desktop expects for volume mounts. MSYS_NO_PATHCONV=1
    # stops the shim from rewriting `/data` inside the container args.
    if [ -n "$MSYSTEM" ] || command -v cygpath >/dev/null 2>&1; then
        MOUNT="$(cd "$HERE" && pwd -W 2>/dev/null || pwd)"
        MSYS_NO_PATHCONV=1 docker run --rm -v "$MOUNT:/data" \
            ghcr.io/asciinema/agg $COMMON_ARGS /data/tour.cast /data/tour.gif
    else
        docker run --rm -v "$HERE:/data" ghcr.io/asciinema/agg \
            $COMMON_ARGS /data/tour.cast /data/tour.gif
    fi
else
    cat <<'EOF' >&2
Neither `agg` nor `docker` is on PATH.

Install one of:
  - agg (Rust):   cargo install --git https://github.com/asciinema/agg
  - Docker:       https://docs.docker.com/get-docker/  (then re-run this script)

The cast file (assets/tour.cast) is committed and renderable — it can also
be uploaded to asciinema.org or rendered with any other agg install.
EOF
    exit 1
fi

echo "wrote $GIF"
ls -lh "$GIF"
